### ISSUE TITLE
Update certificate fingerprint

### ISSUE THREAD

**Issue by danial-k** [hectcastro/terraform-aws-github-actions-oidc#2]
Per this issue https://github.com/aws-actions/configure-aws-credentials/issues/357, the fingerprint has changed.
FYI We also publish a module that dynamically fetches the cert value that may be more future proof: https://github.com/voquis/terraform-aws-github-actions-oidc-role

**Comment by hectcastro** [comment]
Thanks, @danial-k!

Resolved in https://github.com/hectcastro/terraform-aws-github-actions-oidc/pull/3.
